### ISSUE TITLE
Parent package stand-alone build fail in v1.1.0 when use pnpm

### ISSUE THREAD

**Issue by 1natsu172** [aklinker1/buildc#5]
I noticed weird behavior in the wxt monorepo……when do a stand-alone build of `packages/wxt` the build doesn't run (using `pnpm --filter wxt build`, for example).

I looked at the logs and looks like the result of this line here have changed, something must have been broken in the 1.1.0 bun support.
https://github.com/aklinker1/buildc/blob/8564179c53d0fa943133b0a0533fd0f896ef25a6/src/index.ts#L49-L50

In wxt monorepo, it's not completely stuck, because we can avoid by `pnpm i` in root. So no urgent action is needed. This is just a report 🙏

**Comment by aklinker1** [comment]
OK, it's clear I don't understand how `dependency-graph` works... I'll add tests lol

**Comment by aklinker1** [comment]
I did know how it worked, just didn't make enough changes in the previous PR lol. Fix released in `@aklinker1/buildc@1.1.1`, I've already updated WXT.

**Comment by 1natsu172** [comment]
Haha, It happens 😄 It's working fine!
![image](https://github.com/user-attachments/assets/fc5c905d-612b-4255-929b-bc2bc573f9f1)
