### ISSUE TITLE
Update Repo URL

### ISSUE THREAD

**Issue by saidzengin-st** [aklinker1/buildc#7]
### Summary

Repo URL in npm page is wrong

![image](https://github.com/user-attachments/assets/06bc1d93-544e-4b68-9696-a7f16dd93f53)

https://github.com/aklinker1/buildc/blob/c2ed4aab5d561fe2fad385a60dc4c90dcfad99f0/package.json#L38

**Comment by aklinker1** [comment]
Haha thanks
